import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";
import yaml from "js-yaml";

type JsonSchema = {
  type?: string | string[];
  properties?: Record<string, JsonSchema>;
  required?: string[];
  items?: JsonSchema;
  additionalProperties?: boolean | JsonSchema;
  enum?: unknown[];
  nullable?: boolean;
  format?: string;
  description?: string;
  $ref?: string;
  allOf?: JsonSchema[];
  oneOf?: JsonSchema[];
  anyOf?: JsonSchema[];
};

type OpenApiDoc = {
  components?: {
    schemas?: Record<string, JsonSchema>;
  };
};

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, "..", "..", "..");
const specPath = path.resolve(repoRoot, "lib", "api-spec", "openapi.yaml");
// Honor CODEGEN_OUTPUT_ROOT (set by codegen:check) so the drift check can
// write to a throwaway dir instead of the committed working tree. The spec is
// always read from the real repo root.
const outputRoot = process.env.CODEGEN_OUTPUT_ROOT
  ? path.resolve(process.env.CODEGEN_OUTPUT_ROOT)
  : repoRoot;
const outputPath = path.resolve(outputRoot, "lib", "api-zod", "src", "errors.ts");

const COMPONENT_TO_EXPORT: Record<string, string> = {
  Error: "ErrorResponse",
  ValidationError: "ValidationErrorResponse",
};

function schemaToZod(
  schema: JsonSchema,
  components: Record<string, JsonSchema>,
  seen: Set<string> = new Set(),
): string {
  if (schema.$ref) {
    const refName = schema.$ref.replace(/^#\/components\/schemas\//, "");
    if (seen.has(refName)) {
      throw new Error(`Cyclic schema reference detected: ${refName}`);
    }
    const target = components[refName];
    if (!target) {
      throw new Error(`Unknown $ref: ${schema.$ref}`);
    }
    return schemaToZod(target, components, new Set([...seen, refName]));
  }

  if (schema.allOf && schema.allOf.length > 0) {
    const merged: JsonSchema = { type: "object", properties: {}, required: [] };
    for (const sub of schema.allOf) {
      const resolved = sub.$ref
        ? components[sub.$ref.replace(/^#\/components\/schemas\//, "")]
        : sub;
      if (!resolved) {
        throw new Error(`Unable to resolve allOf entry: ${JSON.stringify(sub)}`);
      }
      Object.assign(merged.properties!, resolved.properties ?? {});
      if (resolved.required) merged.required!.push(...resolved.required);
    }
    return schemaToZod(merged, components, seen);
  }

  let expr: string;
  switch (schema.type) {
    case "string":
      expr = "zod.string()";
      break;
    case "integer":
    case "number":
      expr = "zod.number()";
      break;
    case "boolean":
      expr = "zod.boolean()";
      break;
    case "array": {
      const inner = schema.items
        ? schemaToZod(schema.items, components, seen)
        : "zod.unknown()";
      expr = `zod.array(${inner})`;
      break;
    }
    case "object": {
      if (schema.properties && Object.keys(schema.properties).length > 0) {
        const required = new Set(schema.required ?? []);
        const lines: string[] = [];
        for (const [key, value] of Object.entries(schema.properties)) {
          const inner = schemaToZod(value, components, seen);
          const optional = required.has(key) ? "" : ".optional()";
          lines.push(`  ${JSON.stringify(key)}: ${inner}${optional},`);
        }
        expr = `zod.object({\n${lines.join("\n")}\n})`;
      } else if (schema.additionalProperties) {
        const value =
          typeof schema.additionalProperties === "object"
            ? schemaToZod(schema.additionalProperties, components, seen)
            : "zod.unknown()";
        expr = `zod.record(zod.string(), ${value})`;
      } else {
        expr = "zod.object({})";
      }
      break;
    }
    default:
      throw new Error(
        `Unsupported schema type: ${JSON.stringify(schema.type)} in ${JSON.stringify(schema)}`,
      );
  }

  if (schema.nullable) {
    expr = `${expr}.nullable()`;
  }
  return expr;
}

function indent(source: string, prefix: string): string {
  return source
    .split("\n")
    .map((line) => (line.length > 0 ? prefix + line : line))
    .join("\n");
}

function main(): void {
  const raw = fs.readFileSync(specPath, "utf8");
  const doc = yaml.load(raw) as OpenApiDoc;
  const components = doc.components?.schemas ?? {};

  const blocks: string[] = [];
  for (const [componentName, exportName] of Object.entries(
    COMPONENT_TO_EXPORT,
  )) {
    const schema = components[componentName];
    if (!schema) {
      throw new Error(
        `OpenAPI spec is missing required component schema: ${componentName}`,
      );
    }
    const zodExpr = schemaToZod(schema, components);
    const indented = indent(zodExpr, "  ").trimStart();
    blocks.push(`export const ${exportName} = ${indented};`);
  }

  const header = `// Generated by lib/api-spec/scripts/generate-error-zod.ts.
// Do not edit manually. Run \`pnpm --filter @workspace/api-spec run codegen\` to regenerate.
//
// Zod schemas for the OpenAPI \`Error\` and \`ValidationError\` component
// schemas. Orval's zod client only emits schemas for 2xx responses, so the
// 4xx response shapes referenced from the OpenAPI spec do not show up in
// \`./generated/api.ts\`. We derive them here directly from the YAML so they
// can never drift from the spec.

import * as zod from "zod";
`;

  const body = blocks.join("\n\n");
  const output = `${header}\n${body}\n`;
  fs.writeFileSync(outputPath, output, "utf8");

  // eslint-disable-next-line no-console
  console.log(
    `Generated ${path.relative(repoRoot, outputPath)} from ${path.relative(
      repoRoot,
      specPath,
    )}`,
  );
}

main();
