// Generated by lib/api-spec/scripts/generate-error-zod.ts.
// Do not edit manually. Run `pnpm --filter @workspace/api-spec run codegen` to regenerate.
//
// Zod schemas for the OpenAPI `Error` and `ValidationError` component
// schemas. Orval's zod client only emits schemas for 2xx responses, so the
// 4xx response shapes referenced from the OpenAPI spec do not show up in
// `./generated/api.ts`. We derive them here directly from the YAML so they
// can never drift from the spec.

import * as zod from "zod";

export const ErrorResponse = zod.object({
    "error": zod.string(),
  });

export const ValidationErrorResponse = zod.object({
    "error": zod.object({
    "formErrors": zod.array(zod.string()),
    "fieldErrors": zod.record(zod.string(), zod.array(zod.string())),
  }),
  });
