// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/palette-01-midnight-track.tsx": () => import("../components/mockups/palette-01-midnight-track.tsx"),
  "./components/mockups/palette-02-trail-forest.tsx": () => import("../components/mockups/palette-02-trail-forest.tsx"),
  "./components/mockups/palette-03-championship-red.tsx": () => import("../components/mockups/palette-03-championship-red.tsx"),
  "./components/mockups/palette-04-arctic-performance.tsx": () => import("../components/mockups/palette-04-arctic-performance.tsx"),
  "./components/mockups/palette-05-sunset-endurance.tsx": () => import("../components/mockups/palette-05-sunset-endurance.tsx")
};
