import { pgTable, integer, text, jsonb, timestamp } from "drizzle-orm/pg-core";

// The AI Nutritionist report — a deep, body-comp-aware read of how the runner
// is actually doing on protein, fuelling, and recomposition. Generated by Claude
// (Opus 4.8) on top of a deterministic, safety-railed metrics gather, and
// narrated in the coach persona. Single-user → singleton id=1. Expensive to
// produce, so the latest is persisted and only regenerated when the underlying
// metrics change (inputHash mismatch), matching the progress_diagnosis +
// coach-note caching pattern. Both the Today verdict and the Nutrition-page
// deep-dive read this same row so they never disagree.
//
// VISUAL-FIRST CONTRACT (insights rewire): every read is a structured
// `NutritionInsight` — a target-vs-actual comparison with a trajectory. The
// deterministic engine OWNS every numeric field that drives a chart (actual,
// target, floor/ceiling, series, days-on-target, status), so the charts are
// always correct regardless of the model. The AI owns ONLY the words: a one-line
// `caption` per insight and an optional longer `detail` behind a "why", plus the
// single overall `headline` + `narrative`. Less text, more accurate, cheaper.

// Which insight this is. 'fuelling' is the calorie read; protein + carbs are the
// macro reads; bodycomp is the recomposition trajectory (richer series).
export type InsightId =
  | "protein"
  | "carbs"
  | "fat"
  | "fuelling"
  | "hydration"
  | "sodium"
  | "bodycomp";

export type InsightGroup = "macros" | "fuelling" | "hydration" | "sodium" | "body";

// How to read "good": more is better (protein), less is better (—), or stay
// inside a band (sodium between an adequacy floor and a ceiling).
export type InsightDirection = "higher_better" | "lower_better" | "band";

// Where the runner sits. Maps to semantic color in the UI:
//   ahead | on_track | appropriate → success
//   attention | early             → warning
//   under | over                  → destructive
export type InsightStatus =
  | "ahead"
  | "on_track"
  | "attention"
  | "under"
  | "over"
  | "appropriate"
  | "early";

// Per-day adherence for the streak dots.
export type AdherenceHit = "hit" | "close" | "miss" | "none";

export type InsightSeriesPoint = { date: string; value: number };
export type InsightPerDay = { date: string; hit: AdherenceHit };

// A "should-be" overlay: a single goal line, or a goal band (lo..hi).
export type InsightGoal = number | { lo: number; hi: number };

// Body-composition trajectory row — multiple series share one date axis so the
// RecompTrajectory chart can toggle between body-fat %, weight, lean and fat.
export type BodyTrajectoryPoint = {
  date: string;
  weightLb: number | null;
  bodyFatPct: number | null;
  leanLb: number | null;
  fatLb: number | null;
};

// One of the four body stat tiles (Weight / Body-fat / Lean / Fat).
export type BodyStat = {
  key: "weight" | "bodyfat" | "lean" | "fat";
  label: string;
  unit: string;
  value: number | null;
  // Signed change over the window (negative = down). Null when unmeasurable.
  change: number | null;
  // Which direction is the GOOD one for this metric given a recomp/cut, so the
  // trend arrow can be coloured (fat down = good, lean up = good).
  goodDirection: "down" | "up" | "either";
};

// One structured insight: a glanceable target-vs-actual comparison + trajectory.
// The engine fills every field except `caption`/`detail` (the AI's job).
export type NutritionInsight = {
  id: InsightId;
  label: string;
  group: InsightGroup;
  unit: string; // 'g' | 'kcal' | 'oz' | 'mg' | 'lb' | '%'
  actual: number | null;
  target: number | null;
  // Band edges, where they apply (protein floor; sodium adequacy floor/ceiling).
  floor?: number | null;
  ceiling?: number | null;
  direction: InsightDirection;
  // Trend window (logged days), oldest → newest.
  series?: InsightSeriesPoint[];
  // The "should-be" overlay drawn over the series (line or band).
  goal?: InsightGoal | null;
  daysLogged?: number | null;
  daysHit?: number | null; // days on target → feeds the TargetGauge arc
  perDay?: InsightPerDay[]; // streak dots
  status: InsightStatus;
  // --- body-comp only ---
  bodyTrajectory?: BodyTrajectoryPoint[];
  bodyStats?: BodyStat[];
  // The expected recomp end-state band (e.g. body-fat % drifting down) drawn
  // behind the actual line so the "should vs is" gap is visible.
  expectedBand?: { lo: number; hi: number } | null;
  // A short per-metric sub-line for the scorecard tile (engine-computed, where
  // the numbers live): e.g. protein "0.7 g/lb · floor 0.8", carbs "−131 g to
  // target", hydration "+96 oz to go", sodium "aim 2.3–3.5k".
  subMetric?: string | null;
  // --- AI-owned words ---
  caption: string; // ONE short sassy line
  detail?: string; // the longer reasoning, shown behind a "why" expander
};

export type NutritionistReport = {
  weeks: number;
  weeksElapsed: number;
  // One-line plain-language headline of the most important thing right now.
  headline: string;
  // The structured, visual-first reads. Order is significance-ranked (most
  // important first); the UI draws each as a card.
  insights: NutritionInsight[];
  // In-progress PACE coaching for an open day: where today stands vs target and
  // what to prioritise for the rest of the day. Empty string when the day is
  // closed / there's no today data (the panel hides it then).
  today: string;
  // 2-4 concrete next moves, most important first.
  keyMoves: string[];
  // How much to trust this read, given how much was actually logged.
  confidence: "low" | "medium" | "high";
  // Honest list of inputs that would sharpen the diagnosis (e.g. "log body-fat %").
  dataGaps: string[];
  // Coach-voice narration (persona) — the line shown on Today.
  narrative: string;
  // Training counts over the window — feed the scorecard's consistency tile
  // ("N sessions / M wk"). Optional/back-compatible.
  sessionsDone?: number;
  plannedSessions?: number;
};

export const nutritionistReportsTable = pgTable("nutritionist_reports", {
  id: integer("id").primaryKey(), // always 1
  weeks: integer("weeks").notNull(),
  report: jsonb("report").$type<NutritionistReport>().notNull(),
  inputHash: text("input_hash").notNull(),
  generatedAt: timestamp("generated_at", { withTimezone: true }).notNull().defaultNow(),
});

export type NutritionistReportRow = typeof nutritionistReportsTable.$inferSelect;
