import { pgTable, integer, text, jsonb, timestamp } from "drizzle-orm/pg-core";

// The AI Nutritionist report — a deep, body-comp-aware read of how the runner
// is actually doing on protein, fuelling, and recomposition. Generated by Claude
// (Opus 4.8) on top of a deterministic, safety-railed metrics gather, and
// narrated in the coach persona. Single-user → singleton id=1. Expensive to
// produce, so the latest is persisted and only regenerated when the underlying
// metrics change (inputHash mismatch), matching the progress_diagnosis +
// coach-note caching pattern. Both the Today verdict and the Nutrition-page
// deep-dive read this same row so they never disagree.

// One protein lens.
export type ProteinVerdict = {
  // Where the runner sits relative to their recomp protein need.
  status: "too_little" | "on_point" | "too_much";
  // Average daily protein over the window, in grams.
  avgProteinG: number | null;
  // The runner's protein target (g).
  targetProteinG: number | null;
  // Protein per lb of current bodyweight — the recomp-adequacy yardstick.
  gPerLb: number | null;
  // Fraction of logged days that hit target (0..1).
  hitRate: number | null;
  // The substance: adequacy + trend + what it's doing to muscle/recovery.
  detail: string;
  // Timing/distribution guidance (principle-based — we only have daily totals).
  distributionTip: string;
};

// The body-composition diagnosis the runner asked for: where they are, what
// they should be seeing for their goal, and why they may not be — traced to
// their actual inputs (protein, deficit, training, consistency).
export type BodyCompRead = {
  currentWeightLb: number | null;
  bodyFatPct: number | null;
  leanMassLb: number | null;
  fatMassLb: number | null;
  // Signed change over the window (negative = down). Null when bf% is unlogged.
  leanMassChangeLb: number | null;
  fatMassChangeLb: number | null;
  weightChangeLb: number | null;
  inchesChange: number | null;
  // Plain read of the trajectory.
  trend: string;
  // What the trajectory SHOULD look like given the goal + inputs.
  whatYouShouldSee: string;
  // Diagnosis: why it may not be happening, tied to specific inputs.
  whyYouMayNotBe: string;
};

// Fuelling adequacy / deficit safety.
export type DeficitRead = {
  status: "under_floor" | "aggressive" | "appropriate" | "surplus" | "unknown";
  avgCalories: number | null;
  calorieTarget: number | null;
  safeFloorKcal: number;
  detail: string;
};

export type NutritionistReport = {
  weeks: number;
  weeksElapsed: number;
  // One-line plain-language headline of the most important thing right now.
  headline: string;
  protein: ProteinVerdict;
  bodyComp: BodyCompRead;
  deficit: DeficitRead;
  // In-progress PACE coaching for an open day: where today stands vs target and
  // what to prioritise for the rest of the day. Empty string when the day is
  // closed / there's no today data (the panel hides it then).
  today: string;
  // One-line hydration read: how the runner's water intake is helping (or
  // holding back) their nutrition — satiety on a deficit, recovery, protein
  // metabolism. Plain guidance when water isn't logged yet.
  hydration: string;
  // One-line sodium read tuned to the runner: enough for training/performance &
  // blood volume on a hard-training, muscle-building program, without blowing
  // past their ceiling. Plain guidance when sodium isn't logged.
  sodium: string;
  // 2-4 concrete next moves, most important first.
  keyMoves: string[];
  // How much to trust this read, given how much was actually logged.
  confidence: "low" | "medium" | "high";
  // Honest list of inputs that would sharpen the diagnosis (e.g. "log body-fat %").
  dataGaps: string[];
  // Coach-voice narration (persona) — the line shown on Today.
  narrative: string;
};

export const nutritionistReportsTable = pgTable("nutritionist_reports", {
  id: integer("id").primaryKey(), // always 1
  weeks: integer("weeks").notNull(),
  report: jsonb("report").$type<NutritionistReport>().notNull(),
  inputHash: text("input_hash").notNull(),
  generatedAt: timestamp("generated_at", { withTimezone: true }).notNull().defaultNow(),
});

export type NutritionistReportRow = typeof nutritionistReportsTable.$inferSelect;
